// Placeholder catalog shown on first load. The owner replaces or edits all of
// this from the Admin dashboard. Images are generated by scripts/images.py.
import MANIFEST from '../img/manifest.json';

export const CATEGORIES = [
  { id: 'cat-electronics', slug: 'electronics', name: 'Electronics', sort: 1 },
  { id: 'cat-home-kitchen', slug: 'home-kitchen', name: 'Home & Kitchen', sort: 2 },
  { id: 'cat-tools', slug: 'tools', name: 'Tools', sort: 3 },
  { id: 'cat-appliances', slug: 'appliances', name: 'Appliances', sort: 4 },
  { id: 'cat-toys', slug: 'toys', name: 'Toys', sort: 5 },
  { id: 'cat-other', slug: 'other', name: 'Other', sort: 6 },
];

export const SETTINGS = {
  storeName: 'ML Group',
  phone: '(425) 757-2554',
  email: 'Hi@mariotamer.com',
  address1: '',
  city: 'Auburn',
  state: 'WA',
  zip: '',
  pickupHours: 'Monday–Sunday 11am–10pm',
  pickupNote: 'Bring your order number. We load large items for you.',
  announcement: 'Local pickup always available · Ships nationwide · New deals every week',
};

// UPC-A with a valid check digit
function upc(n) {
  const base = ('850316' + String(n * 7919 % 100000).padStart(5, '0')).slice(0, 11);
  let sum = 0;
  for (let i = 0; i < 11; i++) sum += Number(base[i]) * (i % 2 === 0 ? 3 : 1);
  return base + ((10 - (sum % 10)) % 10);
}

const C = (slug) => 'cat-' + slug;
// [slug, title, brand, category, condition, price, originalPrice, shipping, inventory, bestDeal, description]
const ROWS = [
  // Electronics
  ['ultrabook-laptop-16gb-512gb', '15.6" Ultrabook Laptop – 16GB RAM, 512GB SSD', 'Nexa', 'electronics', 'Refurbished', 629, 1099, 19.99, 4, true,
    'Thin aluminum laptop with a 15.6" Full HD display, 12th-gen quad-core processor, 16GB RAM and a fast 512GB SSD. Professionally refurbished, tested and wiped.\n\n• Up to 10 hours of battery\n• Backlit keyboard, fingerprint login\n• Includes 65W USB-C charger\n• 90-day ML Group warranty'],
  ['tablet-with-stylus-64gb', '10.9" Tablet with Stylus – 64GB, Wi-Fi', 'Nexa', 'electronics', 'Open Box', 279, 449, 9.99, 7, false,
    'Bright 10.9" Liquid Retina-style display with a pressure-sensitive stylus for notes and sketching. Open-box unit in excellent condition; screen is flawless.\n\n• 64GB storage, Wi-Fi 6\n• Stylus and USB-C cable included\n• Original box included'],
  ['curved-ultrawide-monitor-34-inch', '34" Curved Ultrawide Monitor – 144Hz', 'Viewpro', 'electronics', 'New', 329, 549, 29.99, 5, true,
    'A 34" 1500R curved ultrawide with 3440×1440 resolution and a 144Hz refresh rate — room for two full windows side by side.\n\n• HDR10, 1ms response\n• Height- and tilt-adjustable stand\n• HDMI ×2, DisplayPort, USB-C 65W'],
  ['4k-ips-monitor-27-inch', '27" 4K IPS Monitor – USB-C', 'Viewpro', 'electronics', 'Open Box', 219, 399, 24.99, 6, false,
    'Sharp 27" 4K IPS panel with 99% sRGB color and single-cable USB-C connection for laptops. Open box, all accessories included.\n\n• 3840×2160, 60Hz\n• USB-C with 65W charging\n• VESA mount compatible'],
  ['mechanical-keyboard-hot-swap', 'Mechanical Keyboard – Hot-Swap, Tactile Switches', 'Keyforge', 'electronics', 'New', 64.99, 129, 8.99, 14, true,
    'Full-size mechanical keyboard with hot-swappable tactile switches and double-shot keycaps in a mixed color set.\n\n• Swap switches without soldering\n• Detachable USB-C cable\n• Per-key backlight'],
  ['wireless-optical-mouse', 'Wireless Optical Mouse – Silent Click', 'Clikr', 'electronics', 'New', 12.99, 29.99, 4.99, 40, false,
    'Comfortable wireless mouse with silent buttons and a precise optical sensor. Plug-and-play USB receiver stores inside the mouse.\n\n• 18-month battery life\n• 1600 DPI\n• Works with Windows, macOS, ChromeOS'],
  ['gaming-desktop-pc-32gb', 'Gaming Desktop PC – 32GB RAM, 1TB SSD', 'Vortex', 'electronics', 'Refurbished', 1149, 1899, 49.99, 2, true,
    'Tempered-glass gaming tower with 8-core processor, 12GB graphics card, 32GB RAM and a 1TB NVMe SSD. Refurbished and stress-tested for 24 hours.\n\n• RGB cooling fans\n• Wi-Fi 6 + Bluetooth\n• Windows installed and activated'],
  ['portable-bluetooth-cd-boombox', 'Portable Bluetooth CD Boombox', 'Soundwell', 'electronics', 'New', 44.99, 89.99, 12.99, 18, true,
    'Retro-styled boombox with a top-loading CD player, Bluetooth streaming and FM radio. Runs on AC power or batteries for the backyard or garage.\n\n• Twin full-range speakers\n• Telescopic FM antenna\n• AUX input and headphone jack'],
  ['ddr4-desktop-memory-32gb', 'DDR4 Desktop Memory 32GB (2×16GB) 3200MHz', 'Corvex', 'electronics', 'New', 54.99, 109.99, 4.99, 22, false,
    'Dual-channel 32GB kit (2×16GB) of DDR4-3200 desktop memory with low-profile heat spreaders.\n\n• CL16, 1.35V\n• Intel XMP 2.0 ready\n• Lifetime limited warranty'],
  ['instant-film-camera-white', 'Instant Film Camera – White', 'Retrolux', 'electronics', 'Open Box', 59.99, 119.99, 8.99, 9, true,
    'Point, shoot and hold a real print in seconds. Built-in flash, selfie mirror and a rechargeable battery. Open box — film not included.\n\n• Auto exposure\n• USB charging\n• Uses standard instant film'],
  ['aluminum-travel-tripod-60-inch', 'Aluminum Travel Tripod – 60"', 'Stablo', 'electronics', 'New', 18.99, 39.99, 7.99, 25, false,
    'Lightweight 60" tripod with a quick-release plate, bubble level and 3-way pan head. Folds down to 20" for travel.\n\n• Supports up to 11 lb\n• Phone clamp included\n• Carry bag included'],
  ['usb-c-charging-cable-3-pack', 'USB-C to USB-A Charging Cable, 6 ft (3-Pack)', 'Voltlink', 'electronics', 'New', 8.99, 19.99, 3.99, 60, false,
    'Braided 6-foot USB-C to USB-A cables for phones, tablets and accessories. Fast-charge and data transfer supported.\n\n• 3A fast charging\n• 10,000+ bend lifespan\n• 3 cables per pack'],
  ['2tb-internal-hard-drive', '2TB Internal Hard Drive – 7200 RPM', 'DataCore', 'electronics', 'Refurbished', 34.99, 79.99, 5.99, 12, false,
    'Reliable 3.5" SATA hard drive for desktop storage upgrades and backups. Factory refurbished, zero bad sectors.\n\n• 2TB capacity, 7200 RPM\n• 256MB cache\n• 1-year warranty'],
  // Home & Kitchen
  ['mid-century-leather-sofa-cognac', 'Mid-Century Leather Sofa – Cognac', 'Hartwell Home', 'home-kitchen', 'Open Box', 849, 1599, 149, 1, true,
    'Three-seat sofa in top-grain cognac leather with a solid wood frame and tapered legs. Open box, never used; minor scuff on the back rail.\n\n• 84" W × 36" D × 34" H\n• Freight delivery or free local pickup\n• Assembly: attach legs only'],
  ['velvet-accent-chair-mango', 'Velvet Accent Chair – Mango', 'Hartwell Home', 'home-kitchen', 'New', 179, 349, 39.99, 3, false,
    'Plush mango velvet accent chair with a curved back, walnut-finish legs and brass details.\n\n• 32" W × 22" D × 27" H\n• Supports up to 300 lb\n• Arrives fully assembled'],
  ['velvet-loveseat-navy', 'Velvet Loveseat – Navy', 'Hartwell Home', 'home-kitchen', 'New', 429, 899, 99, 2, true,
    'Deep navy velvet loveseat with channel-tufted seat cushions and slim gold legs. A statement piece for small spaces.\n\n• 86" W × 40" D × 31" H\n• Kiln-dried hardwood frame\n• Freight delivery or local pickup'],
  ['upholstered-armchair-slate-blue', 'Upholstered Armchair – Slate Blue', 'Hartwell Home', 'home-kitchen', 'Like New', 139, 279, 49.99, 2, false,
    'Comfortable tufted armchair in slate blue fabric with wood legs. Floor model in like-new condition.\n\n• 28" W × 30" D × 33" H\n• Stain-resistant fabric'],
  ['porcelain-teacup-saucer-set', 'Porcelain Teacup & Saucer Set (Set of 4)', 'Maison Blanc', 'home-kitchen', 'New', 22.99, 48, 7.99, 16, false,
    'Fine white porcelain teacups with matching saucers. Dishwasher- and microwave-safe.\n\n• 8 oz cups\n• Set of 4 cups + 4 saucers\n• Gift-boxed'],
  ['glass-serving-dish-with-dome', 'Glass Serving Dish with Dome Lid', 'Maison Blanc', 'home-kitchen', 'New', 26.99, 59, 9.99, 8, false,
    'Hand-blown glass serving dish with a tall dome lid and gold-leaf rim — for olives, pastries or cheese.\n\n• 11" diameter\n• Food-safe glass\n• Hand wash'],
  ['insulated-water-bottle-24-oz', 'Insulated Stainless Water Bottle – 24 oz', 'Trailmate', 'home-kitchen', 'New', 12.99, 29.99, 4.99, 45, false,
    'Double-wall vacuum-insulated bottle keeps drinks cold for 24 hours or hot for 12.\n\n• 18/8 stainless steel\n• Leak-proof screw cap\n• BPA-free'],
  ['white-oak-side-table', 'Scandinavian Side Table – White & Oak', 'Nordhus', 'home-kitchen', 'New', 69, 149, 24.99, 5, false,
    'Round side table with a white top and solid oak splayed legs. Perfect as a nightstand or sofa side table.\n\n• 18" diameter × 20" H\n• Tool-free leg assembly'],
  ['matte-white-pendant-light', 'Matte White Pendant Light', 'Nordhus', 'home-kitchen', 'Open Box', 34.99, 89, 12.99, 11, false,
    'Minimal dome pendant in matte white metal with an adjustable 6 ft cord. Great over kitchen islands.\n\n• 12" shade diameter\n• E26 bulb (not included)\n• Hardwire or plug-in kit'],
  ['glass-bud-vase-faux-stems', 'Glass Bud Vase with Faux Stems', 'Maison Blanc', 'home-kitchen', 'New', 14.99, 34, 6.99, 20, false,
    'Clear glass bud vase with realistic faux flower stems — decor that never needs water.\n\n• 8" tall\n• Stems removable'],
  // Tools
  ['portable-steel-toolbox-20-inch', 'Portable Steel Toolbox – 20"', 'IronLine', 'tools', 'New', 24.99, 49.99, 12.99, 12, true,
    'Heavy-gauge steel toolbox with a removable tray, padlock eye and two metal latches. Powder-coated red finish.\n\n• 20" × 8.5" × 9"\n• Removable cantilever tray\n• Padded carry handle'],
  ['screwdriver-set-6-piece', 'Screwdriver Set – 6 Piece', 'IronLine', 'tools', 'New', 11.99, 24.99, 5.99, 30, false,
    'Six essential screwdrivers — 3 Phillips, 3 slotted — with chrome-vanadium shafts and cushioned two-tone grips.\n\n• Magnetic tips\n• Hanging storage rack included'],
  ['tape-measure-25-ft', 'Tape Measure – 25 ft', 'IronLine', 'tools', 'New', 7.99, 17.99, 4.99, 40, false,
    'Rugged 25 ft tape with a 1" wide blade, slide lock and belt clip. Rubber over-mold survives drops.\n\n• Standout up to 11 ft\n• Magnetic end hook'],
  ['garden-hand-trowel', 'Garden Hand Trowel', 'GreenRow', 'tools', 'New', 5.99, 14.99, 4.99, 35, false,
    'Rust-resistant garden trowel with depth markings and a comfortable grip for planting and potting.\n\n• Stainless steel blade\n• Hanging hole'],
  // Appliances
  ['robot-vacuum-cleaner', 'Robot Vacuum Cleaner – App & Voice Control', 'Cleanbot', 'appliances', 'Open Box', 119, 299, 19.99, 6, true,
    'Slim robot vacuum with LiDAR mapping, 2700Pa suction and 150-minute runtime. Open box, all accessories included.\n\n• Maps rooms and no-go zones\n• Auto-returns to charge\n• Works with voice assistants'],
  ['countertop-microwave-1-1-cu-ft', 'Countertop Microwave – 1.1 cu ft', 'HomeChef', 'appliances', 'Open Box', 79, 149, 29.99, 4, true,
    '1000-watt microwave with 10 power levels, one-touch presets and a turntable. Open box with light shelf wear.\n\n• 1.1 cu ft capacity\n• Child lock\n• Stainless-look door'],
  ['stainless-electric-kettle-1-7l', 'Stainless Electric Kettle – 1.7 L', 'HomeChef', 'appliances', 'New', 24.99, 49.99, 9.99, 14, false,
    'Fast-boil 1500W kettle with a brushed stainless body, water window and auto shut-off.\n\n• 1.7 L capacity\n• Boil-dry protection\n• 360° swivel base'],
  ['stainless-2-slice-toaster', 'Stainless 2-Slice Toaster', 'HomeChef', 'appliances', 'New', 22.99, 44.99, 9.99, 10, false,
    'Wide-slot toaster with 7 shade settings plus bagel, defrost and cancel functions.\n\n• 1.5" wide slots\n• Removable crumb tray'],
  ['glass-door-beverage-cooler', 'Glass-Door Beverage Cooler', 'ChillPro', 'appliances', 'Scratch & Dent', 649, 1499, 199, 1, true,
    'Commercial-grade single-door beverage cooler with LED lighting and adjustable shelves. Scratch & dent: small dent on the left side panel, fully working.\n\n• 12 cu ft\n• 33–41°F temperature range\n• Freight delivery or local pickup'],
  // Toys
  ['vintage-tin-toy-car', 'Vintage-Style Tin Toy Car', 'Tinworks', 'toys', 'New', 19.99, 39.99, 6.99, 12, false,
    'Collectible tin toy car with a glossy two-tone finish and rolling wheels — a nostalgic gift or desk display.\n\n• 7" long\n• Display piece, ages 14+'],
  ['weighted-wooden-chess-set', 'Weighted Chess Set with Board', 'Kingsgate', 'toys', 'New', 34.99, 79.99, 9.99, 7, true,
    'Tournament-size chess set with weighted pieces and a 20" board. A great family game night upgrade.\n\n• 3.75" king\n• Felted piece bases\n• Storage bag included'],
  ['building-bricks-set-500-piece', 'Building Bricks Set – 500 Pieces', 'BrickBox', 'toys', 'New', 17.99, 39.99, 7.99, 24, false,
    'Classic building bricks in 7 colors, compatible with major brick brands.\n\n• 500 pieces\n• Idea booklet included\n• Ages 4+'],
  ['cruiser-skateboard-22-inch', 'Cruiser Skateboard – 22"', 'Rollr', 'toys', 'New', 19.99, 44.99, 9.99, 9, false,
    'Compact 22" plastic cruiser with grippy deck texture and smooth 59mm wheels.\n\n• ABEC-7 bearings\n• Supports up to 200 lb'],
  // Other
  ['aluminum-road-bike-54cm', 'Aluminum Road Bike – 54 cm', 'Veloce', 'other', 'Used – Good', 449, 1099, 89, 1, false,
    'Lightweight aluminum road bike with carbon fork, 18-speed drivetrain and dual-pivot brakes. Tuned up and ready to ride; light cosmetic wear.\n\n• 54 cm frame (fits 5\'6"–5\'10")\n• 700×25c tires'],
  ['4-person-dome-tent', '4-Person Dome Tent', 'Trailmate', 'other', 'Open Box', 59.99, 149.99, 14.99, 6, true,
    'Weather-ready 4-person dome tent with full rainfly, two doors and gear loft. Sets up in about 10 minutes.\n\n• 9\' × 7\' floor\n• Carry bag included'],
  ['commuter-backpack-blue', 'Commuter Backpack – 25 L', 'Trailmate', 'other', 'New', 24.99, 59, 7.99, 18, false,
    'Everyday backpack with padded laptop sleeve, bungee front and breathable back panel.\n\n• Fits 15" laptops\n• Water-resistant fabric\n• Available in blue or gray'],
  ['messenger-bag-black', 'Laptop Messenger Bag', 'Trailmate', 'other', 'New', 22.99, 45, 7.99, 10, false,
    'Structured messenger bag with padded laptop compartment and organizer pockets.\n\n• Fits 15" laptops\n• Adjustable shoulder strap'],
  ['rolling-duffle-bag', 'Rolling Duffle Bag – 80 L', 'Trailmate', 'other', 'New', 34.99, 74, 12.99, 7, false,
    'Large wheeled duffle with a telescoping handle and U-shaped main compartment.\n\n• 80 L capacity\n• Durable ripstop'],
  ['dual-time-analog-watch', 'Dual-Time Analog Watch', 'Harbor & Co.', 'other', 'Open Box', 27.99, 55, 4.99, 6, false,
    'Two-dial analog watch with a brown leather strap — set a second time zone for travel.\n\n• Water-resistant to 50 m\n• Stainless case'],
  ['resistance-band-kit', 'Resistance Band Kit', 'FitCore', 'other', 'New', 11.99, 22, 5.99, 20, false,
    'Complete home-workout band kit with handles, ankle straps, door anchor and carry bag.\n\n• 5 resistance levels\n• Stackable up to 150 lb'],
  ['indoor-outdoor-basketball', 'Indoor/Outdoor Basketball – Size 7', 'Courtline', 'other', 'New', 14.99, 34.99, 8.99, 15, false,
    'Composite leather basketball with deep channels for grip on any court.\n\n• Official size 7\n• Ships deflated'],
  ['live-bonsai-tree', 'Live Juniper Bonsai Tree', 'GreenRow', 'other', 'New', 24.99, 49.99, 14.99, 4, false,
    'Hand-shaped juniper bonsai in a ceramic pot. Arrives with care instructions. Local pickup recommended.\n\n• 6–8 years old\n• 10" tall'],
];

const now = Date.UTC(2026, 8, 20);
export const PRODUCTS = ROWS.map((r, i) => {
  const [slug, title, brand, cat, condition, price, originalPrice, shipping, inventory, bestDeal, description] = r;
  const imgs = (MANIFEST[slug] || []).map((n, k) => ({
    sm: `img/p/${slug}-${n}-sm.webp`,
    lg: `img/p/${slug}-${n}-lg.webp`,
    alt: k === 0 ? title : `${title} – view ${k + 1}`,
  }));
  return {
    id: 'p-' + String(i + 1).padStart(3, '0'),
    slug, title, brand, categoryId: C(cat), condition,
    price, originalPrice, shipping, inventory, bestDeal,
    published: true,
    noShipping: slug === 'live-bonsai-tree',
    upc: upc(i + 11),
    description,
    images: imgs,
    createdAt: new Date(now - i * 36e5 * 7).toISOString(),
  };
});
